SELECT H.HACKER_ID,H.NAME,SUM(SCORE) AS TOTAL_SCORE
FROM
    (
        SELECT HACKER_ID,SUBMISSION_ID,MAX(SCORE) AS SCORE 
        FROM SUBMISSIONS
        GROUP BY HACKER_ID,SUBMISSION_ID
    ) AS S
JOIN HACKERS AS H
ON H.HACKER_ID = S.HACKER_ID
GROUP BY H.HACKER_ID,H.NAME
HAVING TOTAL_SCORE>0
ORDER BY TOTAL_SCORE DESC,H.HACKER_ID;

