SELECT S.NAME
FROM STUDENTS AS S
INNER JOIN FRIENDS AS F ON S.ID = F.ID
INNER JOIN PACKAGES AS P ON S.ID = P.ID
WHERE P.SALARY < (
    SELECT P2.SALARY 
    FROM PACKAGES AS P2 
    WHERE P2.ID = F.FRIEND_ID
)
ORDER BY (
    SELECT P2.Salary
    FROM Packages P2
    WHERE P2.ID = F.Friend_ID
);
