SELECT 
    CASE 
        WHEN GRADES.GRADE<8 THEN 'NULL'
        ELSE STUDENTS.NAME
    END,
    GRADES.GRADE,
    STUDENTS.MARKS

FROM STUDENTS
JOIN GRADES ON STUDENTS.MARKS BETWEEN GRADES.MIN_MARK AND GRADES.MAX_MARK
ORDER BY
    GRADES.GRADE DESC,
    CASE 
        WHEN GRADES.GRADE>=8 THEN STUDENTS.NAME
        END ASC,
    CASE
        WHEN GRADES.GRADE<8 THEN STUDENTS.MARKS
        END ASC
        
    
